# SEGMENTATION FAULT (SEG_FAULT) OCORRE QUANDO 
# O PROGRAMA TENTA ACESSAR UMA PARTE DA MEMÓRIA
# QUE ELE NÃO TEM ACESSO, ESTE ERRO PODE ACARRETAR
# EM PROBLEMAS SÉRIOS COM A SUA MÁQUINA,
# POR ISSO, É RECOMENDÁVEL QUE VOCÊ EVITE ESSE ERRO,
# QUE EXISTE JUSTAMENTE PARA AJUDAR A NÃO CORROMPER
# OS SEUS DADOS NA MEMÓRIA.

print("É isso, mundo!")

def soma_dois(x, y):
  b = x+y
  return b

print(soma_dois)
